[package]
authors = ["Jason Noonan <jason.t.noonan@gmail.com>"]
edition = "2021"
name = "advent-of-code"
version = "0.1.0"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.5.4"

[lib]
bench = false
